### ISSUE TITLE
Don't work on Heroku because of RTM implementation

### ISSUE THREAD

**Issue by acomagu** [lycoris0731/linka#1]
Hi.
It has "Deploy to Heroku" button but don't work well. I tried but `Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch` seemed. This caused because it won't listen the port specified by $PORT env.

linka uses WebSocket and [Heroku supports it](https://devcenter.heroku.com/articles/go-websockets), but it must listen the specified port, not 80 or 443. However, the [nlopes/slack](https://github.com/nlopes/slack) library only listen them defaultly, and we can't change from out of package.

I created [issue on nlopes/slack](https://github.com/nlopes/slack/issues/143) about it 6 days ago, but the reply is not yet. If the issue solved and here will be also, but we can't assume when it is.

That's why, the way for communicating with Slack probably should changed. Or, this problem for only Heroku, so the button should be removed maybe.

**Comment by acomagu** [comment]
Sending pull-request to nlopes/slack is better?

**Comment by ktr0731** [comment]
Thanks for reporting an issue!
I see. Umm...  
As you said, nlopes/slack should use a port number with the envvar.  
However, it's troublesome for me...  

I'll think whether use nlopes/slack which is fixed the issue or use instead of one.

**Comment by acomagu** [comment]
https://github.com/nlopes/slack/issues/143
